version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.15
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=bdec-logogen
      - MYSQL_DATABASE=logogen
    networks:
      springboot-mysql-net:

  server:
    container_name: appserver
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net: